---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-data
  annotations:
    pv.beta.kubernetes.io/gid: "0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
